1. values added: 20
  
2. final result: 20
 
3. values added: 20

5. The code returns a reference error, since result is being called in line 13 which is outside the block it is defined in
